spring:
  application:
    name: kanodays88-ai-agent
  redis:
    host: 192.168.74.100
    port: 6379
    database: 1
    timeout: 5000ms  # 加上连接超时
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 3000ms
      shutdown-timeout: 100ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.74.100:3306/sky_take_out?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: zhangboji88
  ai:
#    openai:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      api-key: ${API_KEY}
#      chat:
#        options:
#          model: qwen3.5-plus
#      embedding:
#        options:
#          model: text-embedding-v3  #向量模型
#          dimensions: 1024   #向量维数
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json #配置mcp服务的配置
    dashscope:
      api-key: ${API_KEY}
      chat:
        options:
          model: glm-5.1
      connect-timeout: 60000
      read-timeout: 120000
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

app:
  baidu:
    api:
      key: ${BaiDuApiKey}